const PREFIX = 'Cart/Checkout/';

// ---billingAddress-----------------------------------------------
export const BILLINGADDRESS_UI_LIST = `${PREFIX}BILLINGADDRESS_UI_LIST`;
export const BILLINGADDRESS_UI_SELECTED = `${PREFIX}BILLINGADDRESS_UI_SELECTED`;
export const BILLINGADDRESS_ON_CREATE = `${PREFIX}BILLINGADDRESS_ON_CREATE`;
export const BILLINGADDRESS_ON_UPDATE = `${PREFIX}BILLINGADDRESS_ON_UPDATE`;
export const BILLINGADDRESS_UI_FORM_SHOW = `${PREFIX}BILLINGADDRESS_UI_FORM_SHOW`;
export const BILLINGADDRESS_UI_FORM_FIELD = `${PREFIX}BILLINGADDRESS_UI_FORM_FIELD`;
export const BILLINGADDRESS_UI_FORM_VALIDATION = `${PREFIX}BILLINGADDRESS_UI_FORM_VALIDATION`;
export const BILLINGADDRESS_UI_FORM_FIELD_VALIDATION = `${PREFIX}BILLINGADDRESS_UI_FORM_FIELD_VALIDATION`;
export const BILLINGADDRESS_UI_FORM_CANCEL = `${PREFIX}BILLINGADDRESS_UI_FORM_CANCEL`;
export const BILLINGADDRESS_UI_COUNTRYSTATE = `${PREFIX}BILLINGADDRESS_GET_COUNTRIES`;
export const BILLINGADDRESS_UI_COUNTRY_SELECTED = `${PREFIX}BILLINGADDRESS_UI_COUNTRY_SELECTED`;


// ---orderSummary-------------------------------------------------
export const ORDERSUMMARY_UI = `${PREFIX}ORDERSUMMARY_UI`;


// ---paymentManager----------------------------------------------
export const PAYMENT_UPDATE_CREDIT_CARD_TYPES = `${PREFIX}paymenManager/PAYMENT_UPDATE_CREDIT_CARD_TYPES`;
export const PAYMENT_UPDATE_SAVED_CREDITCARDS = `${PREFIX}paymenManager/PAYMENT_UPDATE_SAVED_CREDITCARDS`;
export const PAYMENT_UPDATE_SAVED_ECHECKS = `${PREFIX}paymenManager/PAYMENT_UPDATE_SAVED_ECHECKS`;
export const PAYMENT_REGISTER_MODULE = `${PREFIX}paymenManager/PAYMENT_REGISTER_MODULE`;
export const PAYMENT_CHANGE_TYPE = `${PREFIX}paymenManager/PAYMENT_CHANGE_TYPE`;
export const PAYMENT_SELECT_ITEM = `${PREFIX}paymenManager/PAYMENT_SELECT_ITEM`;
export const PAYMENT_ADD_TEMP_CREDIT_CARD = `${PREFIX}paymenManager/PAYMENT_ADD_TEMP_CREDIT_CARD`;
